export const AnimeData = [
  {
    AnimeName: "OnePiece",
    CharName: "Monkey D. Luffy",
    Power: "Hito Hito no Mi, Model: Nika (Gum-Gum Fruit), Gears, Haki",
    Attack_Methods: [
      "Gum-Gum Pistol",
      "Gum-Gum Gatling",
      "Gum-Gum Bazooka",
      "Jet Pistol",
      "Red Hawk",
      "Elephant Gun",
      "Kong Gun",
      "Bajrang Gun",
    ],
    ImageId: {
      "Gum-Gum Pistol": "/Images/GumGumPistol.webp",
      "Gum-Gum Gatling": "/Images/GumGumGatling.jpg",
      "Gum-Gum Bazooka": "/Images/GumGumBazooka.webp",
      "Jet Pistol": "/Images/JetPistol.jpg",
      "Red Hawk": "/Images/RedHawk.jpg",
      "Elephant Gun": "/Images/ElephantGun.jpg",
      "Kong Gun": "/Images/KongGun.jpg",
      "Bajrang Gun": "/Images/BajrangGun.jpg",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Roronoa Zoro",
    Power: "ThreeSword Style, Asura form, Advanced Armament & Conqueror’s Haki",
    Attack_Methods: ["Oni Giri", "Tatsumaki", "Shishi Sonson", "Asura: 12Blade Rush"],
    ImageId: {
      "Oni Giri": "/Images/OniGiri.jpg",
      "Tatsumaki": "/Images/Tatsumiki.gif",
      "Shishi Sonson": "/Images/Shishi.webp",
      "Asura: 12Blade Rush": "/Images/Asura.webp",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Nami",
    Power: "Weather and Navigation Mastery, KlimaTact with Zeus & Stussy",
    Attack_Methods: ["Thunderbolt Tempo", "Mirage Tempo", "Cyclone Tempo", "Basilisk Tempo"],
    ImageId: {
      "Thunderbolt Tempo": "/Images/Thunderbolt.jpg",
      "Mirage Tempo": "/Images/Mirage.jpg",
      "Cyclone Tempo": "/Images/Cyclone.jpeg",
      "Basilisk Tempo": "/Images/Basilisk.jpg",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Tony Tony Chopper",
    Power: "Hito Hito no Mi (Zoan), Rumble Ball Morphs, Medical Ninjutsu",
    Attack_Methods: ["Heavy Point", "Guard Point", "Horn Point", "Monster Point"],
    ImageId: {
      "Heavy Point": "/Images/Heavy.jpg",
      "Guard Point": "/Images/Gaurd.jpg",
      "Horn Point": "/Images/Horn.jpg",
      "Monster Point": "/Images/Monster.jpg",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Nico Robin",
    Power: "Hana Hana no Mi (FlowerFlower Fruit), Archaeological Genius",
    Attack_Methods: ["Clutch", "Seis Fleur", "Gigantesco Mano", "Bird: Gigantesco Fuku"],
    ImageId: {
      "Clutch": "/Images/Clutch.webp",
      "Seis Fleur": "/Images/Seis.jpg",
      "Gigantesco Mano": "/Images/Giga.png",
      "Bird: Gigantesco Fuku": "/Images/Flerus.avif",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Sanji",
    Power: "SkyWalk, Diable Jambe, Raid Suit (Germa 66)",
    Attack_Methods: [
      "Fire Black Leg",
      "Concasse",
      "Diable Jambe: Hell Memories",
      "Sky Walk Kick",
      "Collier Shot",
    ],
    ImageId: {
      "Fire Black Leg": "/Images/Black.jpg",
      "Concasse": "/Images/Concasse.jpg",
      "Diable Jambe: Hell Memories": "/Images/Diable.jpg",
      "Sky Walk Kick": "/Images/sky.jpg",
      "Collier Shot": "/Images/Collier.webp",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Franky",
    Power: "Cyborg Body, ColaPower Boost, Coup de Vent, Franky Family Plans",
    Attack_Methods: ["Strong Right", "Weapons Left", "Coup de Vent", "Franky Flamethrower"],
    ImageId: {
      "Strong Right": "/Images/Strong.webp",
      "Weapons Left": "/Images/Weapons.jpg",
      "Coup de Vent": "/Images/Coup.jpeg",
      "Franky Flamethrower": "/Images/Fflame.webp",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Usopp",
    Power: "Sniping Skills, Pop Greens, Engineering, Observation Haki",
    Attack_Methods: ["Firebird Star", "Impact Wolf", "Sleep Star", "Green Star: Devil"],
    ImageId: {
      "Firebird Star": "/Images/FireBird.jpg",
      "Impact Wolf": "/Images/impact.jpg",
      "Sleep Star": "/Images/Sleep.jpg",
      "Green Star: Devil": "/Images/Green.jpg",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Brook",
    Power: "Yomi Yomi no Mi (ReviveRevive Fruit), Soul King Powers",
    Attack_Methods: ["SoulSolid", "HotCross", "Hummer: Humming Song", "Yomi Yomi no Soul"],
    ImageId: {
      "SoulSolid": "/Images/SoulSolid.webp",
      "HotCross": "/Images/RedHot.jpg",
      "Hummer: Humming Song": "/Images/Humming.jpg",
      "Yomi Yomi no Soul": "/Images/Yomi.avif",
    },
  },
  {
    AnimeName: "OnePiece",
    CharName: "Jimbei",
    Power: "FishMan Karate, FishMan Jujutsu, Deep Water Style",
    Attack_Methods: [
      "Whirlpool Cutter",
      "Leap Over Shark Attack",
      "Jaguar Shark: TwinFin",
      "Shark: Cross Current",
    ],
    ImageId: {
      "Whirlpool Cutter": "/Images/Whirpool.jpg",
      "Leap Over Shark Attack": "/Images/Shark.jpg",
      "Jaguar Shark: TwinFin": "/Images/Jaguar.jpg",
      "Shark: Cross Current": "/Images/Cross.jpg",
    },
  },
  {
    AnimeName: "Naruto",
    CharName: "Naruto Uzumaki",
    Power: "Kurama (NineTails), Sage Mode, Six Paths Powers",
    Attack_Methods: [
      "Rasengan",
      "Shadow Clone Jutsu",
      "Rasen Shuriken",
      "Tailed Beast Bomb",
      "UltraBig Ball Rasenshuriken",
    ],
    ImageId: {
      "Rasengan": "/Images/Rasengan.jpg",
      "Shadow Clone Jutsu": "/Images/Shadow.jpg",
      "Rasen Shuriken": "/Images/RasenShuriken.jpg",
      "Tailed Beast Bomb": "/Images/Tailedbeast.jpg",
      "UltraBig Ball Rasenshuriken": "/Images/UltraBigBallRasenshuriken.jpg",
    },
  },
  {
    AnimeName: "Naruto",
    CharName: "Sasuke Uchiha",
    Power: "Sharingan, Rinnegan, Amaterasu, Lightning Style",
    Attack_Methods: [
      "Chidori",
      "Amaterasu",
      "Susanoo",
      "Indra's Arrow",
      "Inferno Style: Flame Control",
    ],
    ImageId: {
      Chidori: "/Images/Chidori.jpg",
      Amaterasu: "/Images/Ama.jpg",
      Susanoo: "/Images/Susanoo.jpg",
      "Indra's Arrow": "/Images/Arrow.jpg",
      "Inferno Style: Flame Control": "/Images/FlameControl.jpg",
    },
  },
  {
    AnimeName: "Naruto",
    CharName: "Sakura Haruno",
    Power: "Superhuman Strength, Medical Ninjutsu, Byakugou Seal",
    Attack_Methods: [
      "Cherry Blossom Impact",
      "Creation Rebirth",
      "Healing Jutsu",
      "Mitotic Regeneration",
      "Super Punch",
    ],
    ImageId: {
      "Cherry Blossom Impact": "/Images/Cherry.jpeg",
      "Creation Rebirth": "/Images/Rebirth.jpeg",
      "Healing Jutsu": "/Images/Haling.jpeg",
      "Mitotic Regeneration": "/Images/Regeneration.jpeg",
      "Super Punch": "/Images/Superpunch.jpg",
    },
  },
  {
    AnimeName: "Naruto",
    CharName: "Kakashi Hatake",
    Power: "Sharingan, Lightning Release, Space–Time Jutsu",
    Attack_Methods: [
      "Chidori (Lightning Blade)",
      "Kamui",
      "Purple Lightning",
      "Summoning: Ninken",
      "Earth Style Wall",
    ],
    ImageId: {
      "Chidori (Lightning Blade)": "/Images/KChidori.jpg",
      "Kamui": "/Images/Kamui.jpg",
      "Purple Lightning": "/Images/Purple.jpg",
      "Summoning: Ninken": "/Images/Niken.jpg",
      "Earth Style Wall": "/Images/Earth.jpeg",
    },
  },
  {
    AnimeName: "Naruto",
    CharName: "Itachi Uchiha",
    Power: "Mangekyō Sharingan, Genjutsu, Amaterasu",
    Attack_Methods: [
      "Tsukuyomi",
      "Amaterasu",
      "Susanoo",
      "Crow Clone Jutsu",
      "Fire Style: Fireball Jutsu",
    ],
    ImageId: {
      "Tsukuyomi": "/Images/Tsu.jpg",
      "Amaterasu": "/Images/UAma.jpg",
      "Susanoo": "/Images/USusanoo.jpg",
      "Crow Clone Jutsu": "/Images/Crow.jpg",
      "Fire Style: Fireball Jutsu": "/Images/FireBall.jpg",
    },
  },
  {
    AnimeName: "Naruto",
    CharName: "Might Guy",
    Power: "Eight Gates Opening, Taijutsu Master",
    Attack_Methods: [
      "Daytime Tiger",
      "Evening Elephant",
      "Night Guy",
      "Leaf Great Whirlwind",
      "Night Guy Form",
    ],
    ImageId: {
      "Daytime Tiger": "/Images/Daytimetiger.jpeg",
      "Evening Elephant": "/Images/EveningElephant.jpeg",
      "Night Guy": "/Images/Night.jpeg",
      "Leaf Great Whirlwind": "/Images/LeafGreatWhirlwind.jpeg",
      "Night Guy Form": "/Images/NightGuyForm.jpg",
    },
  },
  {
    AnimeName: "Demon Slayer",
    CharName: "Tanjiro Kamado",
    Power: "Water Breathing, Sun Breathing",
    Attack_Methods: [
      "Water Surface Slash",
      "Constant Flux",
      "Hinokami Kagura: Dance",
      "Fire Wheel",
      "Flame Dance",
    ],
    ImageId: {
      "Water Surface Slash": "/Images/WaterSurfaceSlash.jpg",
      "Constant Flux": "/Images/ConstantFlux.jpg", 
      "Hinokami Kagura: Dance": "/Images/HinokamiKagura.jpg",
      "Fire Wheel": "/Images/FireWheel.jpg",
      "Flame Dance": "/Images/Flame dance.jpg",
    },
  },
  {
    AnimeName: "Demon Slayer",
    CharName: "Nezuko Kamado",
    Power: "Demon Blood Art, Regeneration, Size Manipulation",
    Attack_Methods: ["Blood Burst", "Exploding Blood", "SizeShift Kicks", "Bamboo Guard"],
    ImageId: {
      "Blood Burst": "/Images/BloodBurst.jpg",
      "Exploding Blood": "/Images/ExplodingBlood.jpg",
      "SizeShift Kicks": "/Images/SizeShiftKicks.jpg",
      "Bamboo Guard": "/Images/BambooGuard.jpg",
    },
  },
  {
    AnimeName: "Demon Slayer",
    CharName: "Zenitsu Agatsuma",
    Power: "Thunder Breathing",
    Attack_Methods: [
      "ThunderclapandFlash", 
      "Godspeed"
    ],
    ImageId: {
      "ThunderclapandFlash": "/Images/ThunderclapandFlash.jpg",
      "Godspeed": "/Images/Godspeed.jpg",
    },
  },
  {
    AnimeName: "Demon Slayer",
    CharName: "Inosuke Hashibira",
    Power: "Beast Breathing",
    Attack_Methods: ["Fang One  Pierce", "Explosive Rush", "SelfTaught Roar"],
    ImageId: {
      "Fang One  Pierce": "/Images/FangOnePierce.jpg",
      "Explosive Rush": "/Images/ExplosiveRush.jpg",
      "SelfTaught Roar": "/Images/SelfTaughtRoar.jpg",
    },
  },
  {
    AnimeName: "Demon Slayer",
    CharName: "Giyu Tomioka",
    Power: "Water Breathing, BreathofSun hint",
    Attack_Methods: ["Dead Calm", "Water Wheel", "Flowing Dance", "Constant Flux"],
    ImageId: {
      "Dead Calm": "/Images/DeadCalm.jpg",
      "Water Wheel": "/Images/WaterWheel.jpg",
      "Flowing Dance": "/Images/FlowingDance.jpg",
      "Constant Flux": "/Images/ConstantFlux.jpg",
    },
  },
];
