export const QUALIFICATIONS = [
    "10th Pass",
    "12th Pass",
    "Diploma",
    "ITI",
    "Certificate Course",
    "Associate Degree",
    "Bachelor of Arts (BA)",
    "Bachelor of Science (BSc)",
    "Bachelor of Commerce (BCom)",
    "Bachelor of Business Administration (BBA)",
    "Bachelor of Computer Applications (BCA)",
    "Bachelor of Engineering (BE)",
    "Bachelor of Technology (BTech)",
    "Bachelor of Architecture (BArch)",
    "Bachelor of Pharmacy (BPharm)",
    "Bachelor of Education (BEd)",
    "Bachelor of Laws (LLB)",
    "Bachelor of Medicine",
    "Bachelor of Surgery (MBBS)",
    "Bachelor of Dental Surgery (BDS)",
    "Bachelor of Fine Arts (BFA)",
    "Bachelor of Hotel Management (BHM)",
    "Bachelor of Design (BDes)",
    "Postgraduate Diploma",
    "Master of Arts (MA)",
    "Master of Science (MSc)",
    "Master of Commerce (MCom)",
    "Master of Business Administration (MBA)",
    "Master of Computer Applications (MCA)",
    "Master of Engineering (ME)",
    "Master of Technology (MTech)",
    "Master of Architecture (MArch)",
    "Master of Pharmacy (MPharm)",
    "Master of Education (MEd)",
    "Master of Laws (LLM)",
    "Master of Design (MDes)",
    "Doctor of Medicine (MD)",
    "Doctor of Philosophy (PhD)",
    "Doctor of Science (DSc)",
];
