
const COUNTRIES = [
    { name: "Afghanistan", code: "AF", dial: "93", flag: "🇦🇫" },
    { name: "Albania", code: "AL", dial: "355", flag: "🇦🇱" },
    { name: "Algeria", code: "DZ", dial: "213", flag: "🇩🇿" },
    { name: "Andorra", code: "AD", dial: "376", flag: "🇦🇩" },
    { name: "Angola", code: "AO", dial: "244", flag: "🇦🇴" },
    { name: "Antigua and Barbuda", code: "AG", dial: "1268", flag: "🇦🇬" },
    { name: "Argentina", code: "AR", dial: "54", flag: "🇦🇷" },
    { name: "Armenia", code: "AM", dial: "374", flag: "🇦🇲" },
    { name: "Australia", code: "AU", dial: "61", flag: "🇦🇺" },
    { name: "Austria", code: "AT", dial: "43", flag: "🇦🇹" },
    { name: "Azerbaijan", code: "AZ", dial: "994", flag: "🇦🇿" },
    { name: "Bahamas", code: "BS", dial: "1242", flag: "🇧🇸" },
    { name: "Bahrain", code: "BH", dial: "973", flag: "🇧🇭" },
    { name: "Bangladesh", code: "BD", dial: "880", flag: "🇧🇩" },
    { name: "Barbados", code: "BB", dial: "1246", flag: "🇧🇧" },
    { name: "Belarus", code: "BY", dial: "375", flag: "🇧🇾" },
    { name: "Belgium", code: "BE", dial: "32", flag: "🇧🇪" },
    { name: "Belize", code: "BZ", dial: "501", flag: "🇧🇿" },
    { name: "Benin", code: "BJ", dial: "229", flag: "🇧🇯" },
    { name: "Bhutan", code: "BT", dial: "975", flag: "🇧🇹" },
    { name: "Bolivia", code: "BO", dial: "591", flag: "🇧🇴" },
    { name: "Bosnia and Herzegovina", code: "BA", dial: "387", flag: "🇧🇦" },
    { name: "Botswana", code: "BW", dial: "267", flag: "🇧🇼" },
    { name: "Brazil", code: "BR", dial: "55", flag: "🇧🇷" },
    { name: "Brunei", code: "BN", dial: "673", flag: "🇧🇳" },
    { name: "Bulgaria", code: "BG", dial: "359", flag: "🇧🇬" },
    { name: "Burkina Faso", code: "BF", dial: "226", flag: "🇧🇫" },
    { name: "Burundi", code: "BI", dial: "257", flag: "🇧🇮" },
    { name: "Cambodia", code: "KH", dial: "855", flag: "🇰🇭" },
    { name: "Cameroon", code: "CM", dial: "237", flag: "🇨🇲" },
    { name: "Canada", code: "CA", dial: "1", flag: "🇨🇦" },
    { name: "Chile", code: "CL", dial: "56", flag: "🇨🇱" },
    { name: "China", code: "CN", dial: "86", flag: "🇨🇳" },
    { name: "Colombia", code: "CO", dial: "57", flag: "🇨🇴" },
    { name: "Costa Rica", code: "CR", dial: "506", flag: "🇨🇷" },
    { name: "Croatia", code: "HR", dial: "385", flag: "🇭🇷" },
    { name: "Cuba", code: "CU", dial: "53", flag: "🇨🇺" },
    { name: "Cyprus", code: "CY", dial: "357", flag: "🇨🇾" },
    { name: "Czechia", code: "CZ", dial: "420", flag: "🇨🇿" },
    { name: "Denmark", code: "DK", dial: "45", flag: "🇩🇰" },
    { name: "Egypt", code: "EG", dial: "20", flag: "🇪🇬" },
    { name: "Finland", code: "FI", dial: "358", flag: "🇫🇮" },
    { name: "France", code: "FR", dial: "33", flag: "🇫🇷" },
    { name: "Germany", code: "DE", dial: "49", flag: "🇩🇪" },
    { name: "Greece", code: "GR", dial: "30", flag: "🇬🇷" },
    { name: "India", code: "IN", dial: "91", flag: "🇮🇳" },
    { name: "Indonesia", code: "ID", dial: "62", flag: "🇮🇩" },
    { name: "Iran", code: "IR", dial: "98", flag: "🇮🇷" },
    { name: "Iraq", code: "IQ", dial: "964", flag: "🇮🇶" },
    { name: "Ireland", code: "IE", dial: "353", flag: "🇮🇪" },
    { name: "Israel", code: "IL", dial: "972", flag: "🇮🇱" },
    { name: "Italy", code: "IT", dial: "39", flag: "🇮🇹" },
    { name: "Japan", code: "JP", dial: "81", flag: "🇯🇵" },
    { name: "Jordan", code: "JO", dial: "962", flag: "🇯🇴" },
    { name: "Kenya", code: "KE", dial: "254", flag: "🇰🇪" },
    { name: "Malaysia", code: "MY", dial: "60", flag: "🇲🇾" },
    { name: "Mexico", code: "MX", dial: "52", flag: "🇲🇽" },
    { name: "Netherlands", code: "NL", dial: "31", flag: "🇳🇱" },
    { name: "New Zealand", code: "NZ", dial: "64", flag: "🇳🇿" },
    { name: "Nigeria", code: "NG", dial: "234", flag: "🇳🇬" },
    { name: "Norway", code: "NO", dial: "47", flag: "🇳🇴" },
    { name: "Pakistan", code: "PK", dial: "92", flag: "🇵🇰" },
    { name: "Philippines", code: "PH", dial: "63", flag: "🇵🇭" },
    { name: "Poland", code: "PL", dial: "48", flag: "🇵🇱" },
    { name: "Portugal", code: "PT", dial: "351", flag: "🇵🇹" },
    { name: "Qatar", code: "QA", dial: "974", flag: "🇶🇦" },
    { name: "Romania", code: "RO", dial: "40", flag: "🇷🇴" },
    { name: "Russia", code: "RU", dial: "7", flag: "🇷🇺" },
    { name: "Saudi Arabia", code: "SA", dial: "966", flag: "🇸🇦" },
    { name: "Singapore", code: "SG", dial: "65", flag: "🇸🇬" },
    { name: "South Africa", code: "ZA", dial: "27", flag: "🇿🇦" },
    { name: "South Korea", code: "KR", dial: "82", flag: "🇰🇷" },
    { name: "Spain", code: "ES", dial: "34", flag: "🇪🇸" },
    { name: "Sri Lanka", code: "LK", dial: "94", flag: "🇱🇰" },
    { name: "Sweden", code: "SE", dial: "46", flag: "🇸🇪" },
    { name: "Switzerland", code: "CH", dial: "41", flag: "🇨🇭" },
    { name: "Thailand", code: "TH", dial: "66", flag: "🇹🇭" },
    { name: "Turkey", code: "TR", dial: "90", flag: "🇹🇷" },
    { name: "Ukraine", code: "UA", dial: "380", flag: "🇺🇦" },
    { name: "United Arab Emirates", code: "AE", dial: "971", flag: "🇦🇪" },
    { name: "United Kingdom", code: "GB", dial: "44", flag: "🇬🇧" },
    { name: "United States", code: "US", dial: "1", flag: "🇺🇸" },
    { name: "Vietnam", code: "VN", dial: "84", flag: "🇻🇳" }
];
