export const FamousScientists = [
    {
        id : 0,
        name : "Hippocrates",
        lived : "460 – 377 BC",
        Nationality : "Greek",
        Professions: ["Physician"],
        Accomplishments : ["Father of modern medicine", "Linked diseases to natural causes", "Emphasized diet and hygiene"],
        imageId : "images/150/Hippocrates.jpg",
    },
    {
        id : 1,
        name : "Aristotle",
        lived : "384 – 322 BC",
        Nationality: "Greek",
        Professions: ["Philosopher", "Biologist", "Logician", "Physicist"],
        Accomplishments : ["Father of biology", "Linked natural phenomena to observation and reasoning", "Emphasized classification and systematic study."],
        imageId : "wp-content/uploads/2014/05/Aristotle_200.jpg.webp",
    },
    {
        id : 2,
        name : "Euclid",
        lived : "c. 325 – 265 BC",
        Nationality: "Greek",
        Professions: ["Mathematician"],
        Accomplishments : ["Father of modern geometry", "Wrote the influential book Elements", "Laid the foundation for mathematical principles used for centuries"],
        imageId : "images/150/Euclid.jpg",
    },
    //-----17th Century
    {
        id : 3,
        name : "Galileo",
        lived : "1564 – 1642",
        Nationality: "Italian",
        Professions: ["Physicist", "Astronomer", "Engineer", "Mathematician"],
        Accomplishments : ["Created one of the first modern telescopes", "Supported the heliocentric theory of Copernicus", "Laid the groundwork for Kinetics and strength of materials in *Two New Sciences*"],
        imageId : "wp-content/uploads/2014/05/Galileo.jpg.webp",
    },
    {
        id : 4,
        name : "Francis Bacon",
        lived : "1561 – 1626",
        Nationality: "English",
        Professions: ["Philosopher", "Statesman", "Scientist"],
        Accomplishments: ["Father of empiricism", "Advocated the scientific method", "Promoted methodical scientific inquiry for investigating phenomena"],        
        imageId : "wp-content/uploads/2014/06/Francis_Bacon.jpg.webp",
    },
    {
        id : 5,
        name : "Johannes Kepler",
        lived : "1571 – 1630",
        Nationality: "German",
        Professions: ["Mathematician", "Astronomer", "Astrologer"],
        Accomplishments: ["Formulated the laws of planetary motion", "Key figure in the 17th Century Scientific Revolution", "Advanced understanding of celestial mechanics"],
        imageId : "wp-content/uploads/2014/06/Johannes_Kepler.jpg.webp",
    },
    //-----18th Century
    {
        id : 6,
        name : "Antonie van Leeuwenhoek",
        lived : "1632 – 1723",
        Nationality: "Dutch",
        Professions: ["Scientist", "Trader"],
        Accomplishments: ["Father of microbiology", "Discovered single-celled organisms", "Observed muscle fibres, blood flow, and bacteria", "Developed the microscope"],
        imageId : "wp-content/uploads/2014/06/Antonie_van_Leeuwenhoek.jpg.webp",
    },
    {
        id : 7,
        name : "Sir Issac Newton",
        lived : "1642-17263",
        Nationality: "English",
        Professions: ["Physicist", "Mathematician", "Astronomer"],
        Accomplishments: ["Laid foundations for classical mechanics", "Formulated the law of gravity", "Defined the three Laws of Motion", "Made contributions to optics and mathematics"],
        imageId : "wp-content/uploads/2014/05/IsaacNewton-16893.jpg.webp",
    },
    {
        id : 8,
        name : "James Watt",
        lived : "1736 – 1819",
        Nationality: "Scottish",
        Professions: ["Engineer", "Inventor"],
        Accomplishments: ["Improved the Newcomen steam engine", "Created an efficient steam engine", "Paved the way for the Industrial Revolution"],
        imageId : "wp-content/uploads/2014/05/James_Watt2.jpg.webp",
    },
    //-----19th Century
    {
        id : 9,
        name : "Michael Faraday",
        lived : "1791 – 1867",
        Nationality: "English",
        Professions: ["Scientist", "Physicist", "Chemist"],
        Accomplishments: ["Contributed to electromagnetic induction, diamagnetism, and electrolysis", "Advanced the field of electrochemistry", "Discovered carbon and chlorine"],
        imageId : "wp-content/uploads/2014/05/michael-faraday3.jpg.webp",
    },
    {
        id : 10,
        name : "Charles Darwin",
        lived : "1809 – 1882",
        Nationality: "English",
        Professions: ["Scientist", "Naturalist", "Biologist"],
        Accomplishments: ["Developed the theory of evolution", "Collected evidence over 20 years", "Published *On the Origin of Species* (1859)"],
        imageId : "wp-content/uploads/2014/05/charles-darwin4.jpg.webp",
    },
    {
        id : 11,
        name : "Gregor Mendel",
        lived : "1822 – 1884",
        Nationality: "German",
        Professions: ["Scientist", "Augustinian Friar"],
        Accomplishments: ["Founder of modern genetics", "Discovered principles of plant breeding", "Formulated the rules of heredity"],
        imageId : "wp-content/uploads/2014/06/Gregor_Mendel.jpg.webp",
    },
    //-----20th Century
    {
        id : 12,
        name : "Alfred Nobel",
        lived : "1833 – 1896",
        Nationality: "Swedish",
        Professions: ["Chemist", "Engineer", "Innovator", "Armaments Manufacturer"],
        Accomplishments: ["Invented dynamite", "Held 350 patents including a gas meter", "Established the Nobel Prizes"],
        imageId : "wp-content/uploads/2015/02/Alfred_Nobel.jpg.webp",
    },
    {
        id : 13,
        name : "Dmitri Mendeleev",
        lived : "1834 – 1907",
        Nationality: "Russian",
        Professions: ["Chemist"],
        Accomplishments: ["Formulated the Periodic Law", "Standardised the Periodic Table of Elements", "Wrote *Principles of Chemistry* (1868–1870)"],
        imageId : "wp-content/uploads/2014/06/dimitri-Mendeleev.jpg.webp",
    },
    {
        id : 14,
        name : "Marie Curie",
        lived : "1867 – 1934",
        Nationality: "Polish",
        Professions: ["Physicist", "Chemist"],
        Accomplishments: ["Discovered radiation", "Pioneered the application of X-rays", "Won Nobel Prizes in both Chemistry and Physics"],
        imageId : "wp-content/uploads/2014/05/Marie-curie3.jpg.webp",
    },
    //-----21st Century
    {
        id : 15,
        name : "Stephen Hawking",
        lived : "1942 – 2018",
        Nationality: "English",
        Professions: ["Physicist", "Cosmologist", "Author"],
        Accomplishments: ["Authored *The Theory of Everything*", "Wrote *A Brief History of Time*", "Made significant contributions to black hole theory and cosmology"],
        imageId : "wp-content/uploads/2014/05/Stephen_Hawking3.jpg.webp",
    },
]